### ISSUE TITLE
Error when starting game, spacewarpers

### ISSUE THREAD

**Issue by nyqeest** [mattsemar/dsp-personal-logistics#26] opened 2022-02-09 20:15 UTC
After last update when i start the game i occured an error, I think it has something to do with spacewarpers. After start I have 6-8 stacks in my inventory even though I order 1. Yesterday, after the update, I managed to fix the bug by running the game without mod, removing spacewarpers from my inventory, saving and starting again with the mod. Today, after removing the mod, the game starts normally, after turning it on again, the error occurs, as in the picture.

btw, I think your mod is brilliant, it removes unnecessary waiting for items, which is important to me, because after work I only have moments to play. Good job!

![image](https://user-images.githubusercontent.com/52583656/153281625-96496114-59cb-4067-b3c8-25e12244eb47.png)

Edit: Launched after a few tries described above. I think you have to have nothing in the orders

**Comment by mattsemar** [comment] 2022-02-10 01:36
This looks like a bug with the Distribute Space Warpers mod to me

**Comment by nyqeest** [comment] 2022-02-12 14:28
ok maybe you are right but i noticed that when i blocked a supply of items i would restart the game a couple of times and each time spacewarpers would appear in my inventory. one time they did not appear anymore and the game started without errors. I did not try to disable Distribute Space Warpers mod because apparently there are problems with it.

**Comment by mattsemar** [comment] 2022-03-17 05:06
I'm closing this, based on the stack trace it was caused by GalacticTransport. One thing I would mention however is that Personal Logistics does have a hidden keybind to clear errors that just happen one time (counter in red error box is not going up). I made it so CTRL+F3 will clear the error condition so autosaves will be enabled (and the box goes away)

**Closed as completed** 2022-03-17 05:09 UTC
Labels: bug
